version: '3.8'

services:

  backend:
    image: chibiherbie/dongfeng-lend-backend:0.0.1
    build: ./services/backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:ogneogne@db:5432/postgres
    volumes:
      - ./services/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    depends_on:
      - db

#  frontend:
#    image: chibiherbie/dongfeng-lend-frontend:0.0.1
#    build: ./services/frontend
#    volumes:
#      - './services/frontend:/app'
#      - '/app/node_modules'
#    expose:
#      - 8080
#    ports:
#      - "8080:8080"

  db:
    image: postgres:15.1
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ogneogne
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
